name: Build and Release

on:
  push:
    branches:
      - main
      - refs/tags/*
  pull_request:
    branches: [main]

env:
  LINUX_ARTIFACT: jvem.tar.gz
  WINDOWS_ARTIFACT: jvem.zip

jobs:
  common-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tests
        run: cargo test --verbose
      - name: install latest rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true

  build-linux:
    needs: common-build
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: |
          cargo build --all --release
          mv target/release/jvem target/release/jvem_amd64
          mkdir -p target/release/src/utils
          cp src/utils/sources.csv target/release/src/utils
          tar -czvf ${{ env.LINUX_ARTIFACT }} -C target/release/ jvem_amd64

  build-win:
    needs: common-build
    runs-on: windows-latest
    steps:
      - name: build
        run: |
          cargo build --all --release
          mkdir target\release\src\utils
          copy src\utils\sources.csv target\release\src\utils\
          Compress-Archive -Path target\release\* -DestinationPath ${{ env.WINDOWS_ARTIFACT }}

  release:
    needs: [build-linux, build-win]
    runs-on: ubuntu-latest
    steps:
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.LINUX_ARTIFACT }}
            ${{ env.WINDOWS_ARTIFACT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
