name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cargo build --verbose
      - name: tests
        run: cargo test --verbose
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: cargo build --verbose
      - name: tests
        run: cargo test --verbose
